# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 02:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=datetime.datetime(2016, 7, 6, 2, 48, 26, 303885, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
